# Generated by Django 6.0.1 on 2026-01-30 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDB',
            fields=[
                ('Order_No', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=10)),
                ('Address', models.CharField(max_length=100)),
                ('Restraunt_Name', models.CharField(max_length=25)),
                ('Food', models.CharField(max_length=25)),
                ('Quantity', models.IntegerField()),
                ('Total_amt', models.FloatField()),
            ],
        ),
    ]
